apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno-policies
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deploy/policy/k8s/kyverno/policies
  prune: true
  wait: true
  dependsOn:
    - name: infrastructure
