keys:
  # 내 공개키
  - &client age1q4lfv04ytr7d7s8g0l9pnpewpzhhw4fxlx7jn2txwr47tyjn8d3qnl0wa0
  # 서버 공개키
  - &homelab age1c3jrdz0rddh5z7ldeahhuqwuvqvpqhy9ecl72ugsglvrzr58rurslufy58
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *client
          - *homelab
