apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: harbor
      app.kubernetes.io/instance: harbor
      app.kubernetes.io/component: registry
      app.kubernetes.io/part-of: homelab-infrastructure
      app.kubernetes.io/managed-by: flux
    includeSelectors: false
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
