apiVersion: v1
kind: Secret
metadata:
    name: bookorbit-secret
    namespace: bookorbit
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:qf4N95GpxCIWNWSM2V8JYoupx+ZVWpEIoLSFz9Pvt8aOC+zEEj1rPYQqhSpAgYjZ,iv:No1iWyRKIFRvcjo0w0y+493DSyBWdfhngRKPBK4BjGU=,tag:JaLXAnnYIRW3G54ICHP6qQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:3gDLJTdR7PHpNN4Zrfbii7LGXR2n0dYu94RpG4QVPAhXfESUCaEIZ8re56KcnoizU0wroflOR3rVTJPgXGFUrw==,iv:MpccJWVhDgAHevOOpDC7i59HJK+fhItX5Np0sA1zHmE=,tag:uCryi7uZtFFdn4Se0MFjvg==,type:str]
    SETUP_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:+9C0aAJ11xnE1IR3YFDrErlp3Fr7QvXk5EbOFYQ+MPs=,iv:6ktcbXuj790br5YHVQCZ4WYh7R5s8uKzngHjmYhnUus=,tag:cw4m9eTyMjPXg6sXDrWAyA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OWFNbUxuaXc0Z3BCU3BI
            ZnJRZWpXTGJERVVTRFRKVDV0eUllT2RmeXc4CnlSMDN6OGxtbExUQ3U4NWdPTndH
            a29SUG42QW8yQU5IeC9wb29TYmszVmMKLS0tIHhRQmZuK01qN3R5VTZ0VnFRNE9K
            N3ZSR1U1eFpLL3JQZEZJZmxCMFdBdncKIuw9VNWV4te9PDAMwjrNXLdVkQn1Wizk
            0KxwFZOf6naXAblthIqGa+omHAsNK1haGIg2tVgGWVboRfC5Kdn56Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13fmn0qj888sxxfrkmdkxqnw0vfkvejt986rcr900pckm3zxuns8sylm3nw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VTBaa2U2RCs3VnkwRUhF
            WDN4NGpMSmE2eGNRMjFGY3dlU1l5b3ZzS3hNCllubXVyN1QzZXorSWRhMk1mQlJK
            aFpiZXdtU3l4NVRScU5rM3JSTVQrMWMKLS0tIEJsS1IzaXdvdmFraXdLdGF4RGlU
            OVFyMkdVbmRkSmhIOVdRZWZMeDhTYkkKLOhEijsikZ8sdWlPvP43qsppaGUrKk1f
            II2DvXQe0MXV+Jj/h3y7x5m36DsMfGy5vMoHyR1KZOZNWMcwD2eyhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q4lfv04ytr7d7s8g0l9pnpewpzhhw4fxlx7jn2txwr47tyjn8d3qnl0wa0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T07:00:14Z"
    mac: ENC[AES256_GCM,data:+3vuG/J9ewXDNm7k8Vj75EFKef8Wi2vPMGUb3zL33012uDnVIbvTobZNn06UINGdA75j/GRzGfpypgHqL5fD4vIWPaTQkUZMs1fPFDX2yvylcHrQCxbwxkBm3aYP7lVgaWcxOdr/mF4k8Fgp5xra4ntWF1abaWTI2lVvtjx3IpA=,iv:ZBZxzGs1Zv1nvoYdHXx192dVrJkDixBmKsdsm4UtJZI=,tag:JooACEkK4j6wBqsoICTJMg==,type:str]
    version: 3.13.1
