apiVersion: v1
kind: Secret
metadata:
    name: bookorbit-secret
    namespace: bookorbit
type: Opaque
stringData:
    #ENC[AES256_GCM,data:KsmRDtvElPEnTLNO/DD8jROhLmMD6NMsGTNasyVXb28+5BEF9Ko+liJm/rkSo5GHpQ==,iv:YDP2XaSw19FSb/DVsG856U8Xopp7no3LzyLgHhdiPa0=,tag:z28ByNYuCGaswg/SV7pvVg==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:rYpR8jAJAKj60L9aJWd5tmC963NeG6LtEtEyHDmhqUOk3BcKagwBLObS6VV8eHGk,iv:QMF8MIdVuPEe4qTuNss5VOA99h1vEq5EaP2DhxfwTd4=,tag:BHlvVK0O/PAjpufABNuhAA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:DBBg/GkUCB4MDJQIy5L/OXVBwVw8LZBhW3fbmCwAj+GWo4uJUcKw6FjQefWfTEPJ1JVOIgtLwm0PolMkgapnSw==,iv:ytmSgMmodwOk3gLA/iS1aF1+v+n3I77GISIET0V3Iw0=,tag:kHdKkasf403sRMkoZMOhMg==,type:str]
    SETUP_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:hi9DuiDeN49ERFf+yK+ZBtp8Z8379rt9Xkzj2zC2fZs=,iv:3LFYUW1TRr1mEDO/wxasGVbFR93sDLAs3AmzW4xuOU4=,tag:oRfqYSX8w37J631p+Rvgiw==,type:str]
    #ENC[AES256_GCM,data:oSZcBlKmGtMnIa/0wtLc62GACtQdGTv68b2wfEi2MgkZP4Bj4htUtsCWs7rFzWnnl3bbh3t7t8NL,iv:5xYYgI0335A/VZgTkJfmpYy8X+g2ZkH36Ws2pnX8GH8=,tag:FWHBlSrUcH0S9pBp4w4ZnA==,type:comment]
    ADMIN_USERNAME: ENC[AES256_GCM,data:KR/l1jY=,iv:k+lkNsyx+UUMq3WygXO5VUAFxQKBkvNnBemx/IKH8mM=,tag:24/4ni35/Y9lcXvrUbZtTw==,type:str]
    ADMIN_NAME: ENC[AES256_GCM,data:ERQH1J+WxrZS,iv:ZqvO1Hs86QSloZGhCaruU3aUbxn3p1Rrsp1qlG0Ea5M=,tag:1UavfWXWLaeZ3ziB+c+GLg==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:p2zBssY770kXgDE0dNbNFMZlY+jKK91adQ==,iv:zLljMA1XHigLYEiO06P+Lj0qW1MGlsPuJLSKIgy1sEE=,tag:rj9iZKzBEE5ANJ0iacJy5Q==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:+5Lg/hyxgpDuqzzoeXqUW5RUtxhv9FTm,iv:Lu/RADRO+stFMvTgDXp6xcSkRtQfQyCQbnkRa1hgkLk=,tag:ShSZcFs0R1GvK3FrF21/vA==,type:str]
    #ENC[AES256_GCM,data:fLG0kcs3uE4n3ftjJlfaHxzkABirZ/dcxIWHrTzHyM8zMJHW8pnXbTPHZ8fEkkM5chFrMkc=,iv:S9WD2m3X9PqvUUF5vvlFI5WnAMUskaayduz9/pI5B+4=,tag:WOw/GpbhrunXwfgczY9eUw==,type:comment]
    USER_ALINA_USERNAME: ENC[AES256_GCM,data:2Ds1GsU=,iv:W9yCafzajWR2mO+Sd5Ne30DgOGPXdp+yUKkhikqFjmg=,tag:AE9CtZiK0IQp43xejTnALg==,type:str]
    USER_ALINA_NAME: ENC[AES256_GCM,data:arBOqps=,iv:8dDMLJFhN01/G1o6VmKDtmCSRunoENKQuYYEp+ZnRTA=,tag:PsBqlMbg1is2t2UyHiQPTw==,type:str]
    USER_ALINA_EMAIL: ENC[AES256_GCM,data:02bkRXP6l0mkFf8PonXB2lbv1g==,iv:EnjHm13Vsk9Nn0a7x24fnqmUtkUfBDDBU0u3Zzggo6k=,tag:BgNnm4sFRR9UW1S/57QceQ==,type:str]
    USER_ALINA_PASSWORD: ENC[AES256_GCM,data:EdFBwEfZ+tEhgHzFFp1sl5yAlOD+vytP,iv:8mbR49KToCiSsOBOsA8NsQh57m1/P92ZVduqY6c6yAY=,tag:hde+vayECP/n03qx4q8fSQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVVUxZnRXa3k0cHJNdVRW
            R2ViUzFkKzVHVmxyMmFvNlpXd3h3TFB0bFZzCjdjRytweXplOGI3VjBMSDZCcm1h
            aWhIQi9jL0s1THJJaE10V0kxLzVxNW8KLS0tIDdMVjVuRXBSVTVUS3hLdXRVUVJo
            UkJSTkdNeDQxaHhDamFtYlpYdlNuaFkKxkmDwkOTbsBoQjwgIuKxaCBmZVXZ7vA0
            rvpUWJKTHnXgxDn08/cU6QfnnchO7FovQvKDCwQenL8YgzWD/JvVLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13fmn0qj888sxxfrkmdkxqnw0vfkvejt986rcr900pckm3zxuns8sylm3nw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKN3FqeERyY1Z2S3VsaG83
            RFhTbk1hWTZrVXJHWWRqZnEweXd4bU92S0VjCmJtVVkzSHUrRFRyS0xOeEdnc2Mv
            bUU3NmpMMkFLZkppdkF2RFg1VmJJR1EKLS0tIEtmeU1RY3Rjamo0VkdpS3luZlNE
            aGZZMzVKOUczcmdhSll0QzZvcFQ0cmcKu42KibB3RzsVgzSCYeyfQbVHXCO/K9PH
            7cf0scWrbNgEHeHULQe81tok7cRCLlWCBeLVM8gLCWgo9T8RMK1ofg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q4lfv04ytr7d7s8g0l9pnpewpzhhw4fxlx7jn2txwr47tyjn8d3qnl0wa0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T16:26:43Z"
    mac: ENC[AES256_GCM,data:tyugZ0I40QX50B9V2RVON8HtJmLWCfHK79vq7WGkDF0+eSZHHYIdHAK+c/VOcYlqwFFsFcvQiCXkd5L0+pkdVIjc0QCMcZqKJcgLu9KXOutMxy03JGMzsRqGOzHwcM7Y201LDz7HMuvI0AOaVTM/RGf2Ig9GyS8eRDHMuck1Kdc=,iv:XsF97O2Kmq6qAOvMPGCSul43Ngi9qRgQxFHWxsLlOvw=,tag:ZCXhYkvA1agLyJeWYDIaMg==,type:str]
    version: 3.13.1
