apiVersion: v1
kind: Secret
metadata:
    name: bookorbit-setup
    namespace: bookorbit
type: Opaque
stringData:
    ADMIN_USERNAME: ENC[AES256_GCM,data:83z0rRE=,iv:DTTZYR1raPWD0Eft40tY0+BRTg8uzVrsNfguYhpunUM=,tag:tKJECBMk1/p+P4fHbK0rsA==,type:str]
    ADMIN_NAME: ENC[AES256_GCM,data:v+I8xHWdIqX+,iv:Of4/8TY4o4Lx6I43V7ROsXzfGRWCr9vPk6BNeQGH28A=,tag:l7ePP++Tb1X8H7qflZ++HA==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:2akJ+SH7BBlD39sKmwfiLxGC2frB6g6kug==,iv:DotnfEE5FTb6Y2ZYkpxWgJ1TGJVnlTIKmgiC/5NsI2E=,tag:G4rI7NW9cOe516Yd5RhQWw==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:rYWTazZZ2Ks0hUy1fzM2l6yhAOrTA7UUCU7y,iv:zFhU/K4OsE/GZeWkDPRBsZtb9Dn/HCdVgm16HAI1qkU=,tag:sHJK0fzWb3dypBo1kh9R/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MjFRZ1ZUNmFjZTE1Y1Fv
            bitnME5ON3Ryb0JZZjdUWm4wVHk5N25mdEZVCmZVSDRPV2NFanNuL3pyclJwaVd5
            SmFpZ25NOGw4cGV5VDVpM2x4UTRMZ1UKLS0tIDhEbEsxRzdTVnN5SHRNS05SaTVr
            SkNzUkJNY2dTWnV1UkxxRlIxaGN4R2sK26JMIc6BVIOwb9qdSBoNtT9NbbfYc/ol
            LXKuU/xJ+wxgZy23MtHkal/khJGExc5qkUtErE3i4+4cpbxh2OrMVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13fmn0qj888sxxfrkmdkxqnw0vfkvejt986rcr900pckm3zxuns8sylm3nw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZTlacm9NT3pZRTNIMXh4
            TDhOWkg0RDJ2Mk16Z2NJMkc2TTEydkhieTJVCmtPK3JLemc5ckRrT3hHZXk3aS9P
            aENFcEs0cjNuSFBvaHNvRGE2T2FzU3MKLS0tIGgwNzNsUlBocm1qTHR1cC8xb0tV
            R3Q4WGxQMkl1WVRwZng0dFdudU9Ya2cKEQhcVrmJjr3MLyl1C7scwNu/okEbWoUF
            ih/FTP0Pu2ADPeag1g2RE62re6x+/2WbPZtaa1QmFf43kfg2juPspA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q4lfv04ytr7d7s8g0l9pnpewpzhhw4fxlx7jn2txwr47tyjn8d3qnl0wa0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T13:34:14Z"
    mac: ENC[AES256_GCM,data:L9i8FrwgS5HljlrmeHP5DsL2VHe7fY5kGfm7Rp0jmPLFwejQ6Wvs2qg5n0zzPxAWSIunaPiNBKyzyqj5YqykWvURGkrLxhG/XyXOACprbta8+8U/8CK+Q5pQT/PWZ6Rn+0SQDY+2fFK1yg4EkhTjmbEuYEEF9O8BR3d6GhxbISQ=,iv:orVGoa9vk1+ASemZw/WAewoCibHmXr+0inGHozWgQpU=,tag:FCSW8wZQl2His+mP+8+fHw==,type:str]
    version: 3.13.1
