#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
app="${APP:-${2:-tonys-gis}}"
action="${1:-check}"

generated_header='# Code generated by the platform renderer.
# Source: deploy/platform/apps/'"$app"'.cue
# DO NOT EDIT.
'

if [ -n "${CUE:-}" ]; then
    cue_cmd=("$CUE")
elif command -v cue >/dev/null 2>&1; then
    cue_cmd=(cue)
else
    cue_cmd=(nix run nixpkgs#cue --)
fi

build_context() {
    local dst="$1"

    mkdir -p "$dst"
    find "$repo_root/deploy/platform" \
        -type f \
        -name '*.cue' \
        ! -path '*/cue.mod/*' \
        ! -path '*/tests/*' \
        -print0 |
        while IFS= read -r -d '' file; do
            cp "$file" "$dst/$(basename "$(dirname "$file")")-$(basename "$file")"
        done
}

build_test_context() {
    local dst="$1" fixture="$2"

    mkdir -p "$dst"
    find "$repo_root/deploy/platform" \
        -type f \
        -name '*.cue' \
        ! -path '*/cue.mod/*' \
        ! -path '*/apps/*' \
        ! -path '*/tests/*' \
        -print0 |
        while IFS= read -r -d '' file; do
            cp "$file" "$dst/$(basename "$(dirname "$file")")-$(basename "$file")"
        done
    cp "$repo_root/deploy/platform/tests/$fixture/app.cue" "$dst/test-app.cue"
}

cue_export_yaml() {
    local ctx="$1" expr="$2" out="$3"

    (cd "$ctx" && "${cue_cmd[@]}" export . -e "$expr" --out yaml) > "$out"
}

render_app() {
    local target="$repo_root/deploy/k8s/generated/apps/$app"
    local ctx tmp

    tmp="$(mktemp -d)"
    ctx="$tmp/context"
    build_context "$ctx"

    (cd "$ctx" && "${cue_cmd[@]}" vet .)
    (cd "$ctx" && "${cue_cmd[@]}" export . -e "rendered[\"$app\"]") >/dev/null

    rm -rf "$target"
    mkdir -p "$target"

    render_one "$ctx" "rendered[\"$app\"].namespace" "$target/namespace.yaml"
    render_one "$ctx" "rendered[\"$app\"].serviceAccount" "$target/serviceaccount.yaml"
    render_one "$ctx" "rendered[\"$app\"].deployment" "$target/deployment.yaml"
    render_one "$ctx" "rendered[\"$app\"].service" "$target/service.yaml"
    render_one "$ctx" "rendered[\"$app\"].httpRoute" "$target/httproute.yaml"
    {
        printf '%s\n' "$generated_header"
        (cd "$ctx" && "${cue_cmd[@]}" export . -e "rendered[\"$app\"].networkPolicies.defaultDeny" --out yaml)
        printf '%s\n' '---'
        (cd "$ctx" && "${cue_cmd[@]}" export . -e "rendered[\"$app\"].networkPolicies.workload" --out yaml)
    } > "$target/networkpolicy.yaml"
    render_one "$ctx" "rendered[\"$app\"].kustomization" "$target/kustomization.yaml"
}

render_one() {
    local ctx="$1" expr="$2" out="$3"

    {
        printf '%s\n' "$generated_header"
        cue_export_yaml "$ctx" "$expr" /dev/stdout
    } > "$out"
}

render_all() {
    APP=tonys-gis render_app
    render_generated_root
}

render_generated_root() {
    mkdir -p "$repo_root/deploy/k8s/generated/apps"
    cat > "$repo_root/deploy/k8s/generated/apps/kustomization.yaml" <<'EOF'
# Code generated by the platform renderer.
# Source: deploy/platform/apps/*.cue
# DO NOT EDIT.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tonys-gis
EOF
}

check_invalid_fixture() {
    local fixture="$1"
    local ctx tmp

    tmp="$(mktemp -d)"
    ctx="$tmp/context"
    build_test_context "$ctx" "$fixture"
    if (cd "$ctx" && "${cue_cmd[@]}" export . -e 'rendered["invalid"]') >/dev/null 2>&1; then
        echo "Expected invalid fixture to fail: $fixture" >&2
        return 1
    fi
}

check_app() {
    local tmp before after

    tmp="$(mktemp -d)"

    cue_files=()
    while IFS= read -r file; do
        cue_files+=("$file")
    done < <(find "$repo_root/deploy/platform" -type f -name '*.cue' ! -path '*/cue.mod/*' | sort)
    "${cue_cmd[@]}" fmt "${cue_files[@]}"
    APP="$app" render_app
    render_generated_root

    kustomize build "$repo_root/deploy/k8s/generated/apps/$app" > "$tmp/rendered.yaml"
    kubeconform -summary -strict -ignore-missing-schemas "$tmp/rendered.yaml"

    before="$tmp/before"
    after="$tmp/after"
    mkdir -p "$before" "$after"
    cp -R "$repo_root/deploy/k8s/generated/apps/$app/." "$before/"
    APP="$app" render_app
    diff -ru "$before" "$repo_root/deploy/k8s/generated/apps/$app" > "$tmp/deterministic.diff" || {
        cat "$tmp/deterministic.diff" >&2
        return 1
    }

    check_invalid_fixture invalid-missing-digest
    check_invalid_fixture invalid-missing-route-host
    check_invalid_fixture invalid-port
    check_invalid_fixture invalid-missing-resources
}

check_generated() {
    local tmp

    tmp="$(mktemp -d)"
    cp -R "$repo_root/deploy/k8s/generated" "$tmp/generated-before" 2>/dev/null || mkdir -p "$tmp/generated-before"
    render_all
    diff -ru "$tmp/generated-before" "$repo_root/deploy/k8s/generated"
}

diff_generated() {
    local tmp

    tmp="$(mktemp -d)"
    cp -R "$repo_root/deploy/k8s/generated" "$tmp/generated-before" 2>/dev/null || mkdir -p "$tmp/generated-before"
    render_all
    diff -ru "$tmp/generated-before" "$repo_root/deploy/k8s/generated" || true
}

clean_generated() {
    rm -rf "$repo_root/deploy/k8s/generated"
}

case "$action" in
    render) render_app; render_generated_root ;;
    render-all) render_all ;;
    check) check_app ;;
    check-all) check_app ;;
    check-generated) check_generated ;;
    diff-generated) diff_generated ;;
    clean-generated) clean_generated ;;
    *)
        echo "Usage: $0 {render|render-all|check|check-all|check-generated|diff-generated|clean-generated} [app]" >&2
        exit 2
        ;;
esac
