name: Nix Setup
description: Checkout + Nix + Cache + git-crypt unlock
inputs:
  git-crypt-key:
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: DeterminateSystems/nix-installer-action@v21
    - uses: DeterminateSystems/magic-nix-cache-action@v13
    - name: Unlock git-crypt
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y git-crypt
        echo "${{ inputs.git-crypt-key }}" | base64 -d > ./git-crypt.key
        git-crypt unlock ./git-crypt.key
        rm ./git-crypt.key
