---
name: CI
on:
    pull_request:
        branches: [main]
        paths: ["**.nix", "flake.lock", ".github/**", "justfile", "k8s/**", "policy/**"]
    push:
        branches: [main]
        paths: ["**.nix", "flake.lock", ".github/**", "justfile", "k8s/**", "policy/**"]
    merge_group:
concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/nix-setup
              with:
                git-crypt-key: ${{ secrets.GIT_CRYPT_KEY }}
            - run: nix develop -c just check
