name: Flake Update
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@33c9ab3ef95cd57c164d9d6eb1f9a46338538d41
      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@55718cd9ebf1737a061487d5ada21abf31e99a98
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@ec13d37c32ca75bc750ecc133e944e5a18164688
        with:
          pr-title: "chore(deps): update flake dependencies"
          pr-labels: |
            dependencies
            automated
          token: ${{ secrets.GITHUB_TOKEN }}
          push-to-flakehub: false
